Mc dl genericiserer 4368
ONSdigital/es-enrichment-sg pull request #19
Opened 2019-11-19 16:04 UTC by kingmushroom

making generic. Tested on aws(happy to show) , with both sandy and blocks lookups n data.

2019-11-19 16:38 UTC, KrisRogos requested changes
The following sections don't match the current naming convention. Everything else is fine.

2019-11-19 16:38 UTC, KrisRogos commented on tests/test_enrichment.py
> +                       "required": ["region", "marine"]}},
Column names are not separated with `_`, `-` or differentCase

2019-11-19 16:38 UTC, KrisRogos commented on tests/test_enrichment.py
> +                      "joincolumn": "county",
Same as above

2019-11-19 16:38 UTC, KrisRogos commented on tests/test_enrichment.py
> +                            "joincolumn": "fred"}}, "parameters": parameters}
And again

2019-11-19 16:52 UTC, KrisRogos approved these changes

2019-11-20 14:08 UTC, glanvl approved these changes
Looks all fine to me. Tests ran fine locally and also tested on AWS with triggering the wrangler. All worked fine and produced the output with the required columns. The only possible change which I would suggest (could be left as tech debt) would be to have the JSON lookup "Lookup_info" environment variable into a file as a separate config.

2019-11-20 14:09 UTC, merged